Fix: [Installer] PyInstallerを最新版に更新
インストール時に発生するエラーを修正:

[31927] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib/parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[31927] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

https://github.com/pyinstaller/pyinstaller/issues/7692